name         'thomasvandoren-redis'
version      '0.0.9'
author       'Thomas Van Doren'
license      'BSD'
project_page 'https://github.com/thomasvandoren/puppet-redis'
dependency   'maestrodev/wget'
dependency   'puppetlabs/gcc'
