name    'maestrodev-wget'
version '1.3.1'
source 'http://github.com/maestrodev/puppet-wget.git'
author 'maestrodev'
license 'Apache License, Version 2.0'
summary 'Download files with wget'
description 'A module for wget that allows downloading of files, supporting authentication'
project_page 'http://github.com/maestrodev/puppet-wget'
